### PR TITLE
Add Occidental (Interlingue) for Chapter 6

### PR DESCRIPTION
**Pull request by Dhghomon**

### CODE REVIEW

**Comment by richardanaya** [comment]
Published! https://tourofrust.com/beta_chapter_6_ie.html

**Comment by Dhghomon** [comment]
@richardanaya Does that link work for you? I can't see it yet.

**Comment by richardanaya** [comment]
Not sure what happened, the property for beta: true got mixed up with everything :) try now https://tourofrust.com//beta_chapter_6_ie.html

**Comment by Dhghomon** [comment]
Looks good now! 

By the way, I added an extra comment in the translated page on raw string literals about how you can just bump up the # count as much as you want if you have a string with "# in it:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&code=fn%20main()%20%7B%0A%20%20println!(r%23%23%22Let%27s%20talk%20about%20the%20%0Ausage%20of%20the%20two%20%22%23%20characters%20in%20string%20literals%22%23%23)%3B%0A%7D

**Pull request merged**
