### PR TITLE
[EN] Memory regions - Update grammar

### PR DESCRIPTION
**Pull request by simeg**
A few mistakes corrected and some changes to make it read better (IMO).

Feel free to challenge me on my changes.

### CODE REVIEW

**Comment by richardanaya** [comment]
This looks great!

**Comment by richardanaya** [comment]
@jassler @Dhghomon @knightpp @albatraduce @Denstone @mgemard @spartucus 

 in case it helps inspire ideas in other languages

**Comment by richardanaya** [comment]
@simeg I don't want to bother you if you aren't interested :) but would you be interested in beta-reading new chapters?

**Comment by simeg** [comment]
@richardanaya Sure, I'm interested :)

**Comment by simeg** [comment]
@richardanaya You can email me s.egersand@gmail.com, or how do you plan on sharing the content?

**Pull request merged**
