### PR TITLE
[HU] Clean up

### PR DESCRIPTION
**Pull request by bugadani**
This PR is a work in progress aimed to make the Hungarian translation more friendly and less verbatim. While not nearly ready, it's public so that others may review the changes.

### CODE REVIEW

**Comment by Nemin32** [comment]
Hey thanks for the help, a lot of your stuff really does flow better.

**Comment by bugadani** [comment]
While I still think there are some improvements to make here, let's call it quits for now :) I'd be happy to read any feedback on this!

**Comment by richardanaya** [comment]
@bugadani FYI, I think it's best to use `|` 
some time ago we split up this huge yaml file into many yaml files and the parser kind of had it's own opinion :) check out some examples that use `|`

**Comment by richardanaya** [comment]
@bugadani I deployed this if you want to see what the latest looks like

**Comment by bugadani** [comment]
Thanks, looks like I have a ton of fixing to do 😂

**Pull request merged**
