### PR TITLE
Added German language for chapter 1

### PR DESCRIPTION
**Pull request by jassler**
Didn't change code - should that be changed, too?
Also, Basic types was a little nontrivial to translate. Someone should maybe take a look.

### CODE REVIEW

**Comment by richardanaya** [comment]
Thank you so much! It would be a nice to have. Right now, it will just fall back onto the english code examples. To add localized code examples would would just involved a "code_de" property.  I can merge this PR and we can add into a future PR if you'd like?

**Comment by jassler** [comment]
Hey, yeah sure!
I don't think the examples would change much though - at least from my experience in Germany, source code (including comments) usually is (and probably should) be written in english, so I think it'd make sense for the examples to stay this way :)

**Comment by richardanaya** [comment]
It's live! thanks again :)

**Comment by jassler** [comment]
How / at what frequency do you plan to release new chapters?

Also btw, then language is "Deutsch", not "Deutsche" :)

**Comment by richardanaya** [comment]
Hi! Thank you so much. I’m actually working on chapter 2 this week :) feel free to submit as many PR you like!

**Comment by richardanaya** [comment]
Also, I set up the generator so languages don’t all have to have the same number of pages so you can work at the pace you like

**Pull request merged**
