### PR TITLE
Add Occidental (Interlingue) for Chapter 3

### PR DESCRIPTION
**Pull request by Dhghomon**

### CODE REVIEW

**Comment by richardanaya** [comment]
Awesome job!

**Comment by richardanaya** [comment]
Published at https://tourofrust.com/beta_22_ie.html  .  How'd you you like the process this time?

**Comment by Dhghomon** [comment]
Felt about the same! I'm okay with pretty much any format, it seems.

By the way, I've let the Korean Rust Discord know about the tour and hopefully someone will translate it into Korean eventually. But in the meantime the English version is easy enough too. Comment from this morning:

몇 주 전에 A Tour of Go의 러스트 버전이 나왔는데 제가 Interlingue (Occidental) 번역을 했고 다른 사람들이 독일어 등 번역을 다 했고 한국어판도 나오면 되겠네요 https://tourofrust.com/
(Me yesterday: "A few weeks ago a Rust version for A Tour of Go came out and I did the translation into Interlingue (Occidental), some others did German etc. and would be nice if a Korean version came out")

@Dhghomon tourofrust 정말 쉽게 가르쳐주는것 같네요. 확실히 프로그래밍 초보자도 이해하기 쉽도록요. 정말 감사합니다!
(Other person: "Wow, it really does a good job explaining it easily. It's definitely easy to understand for someone new to programming. Thanks a lot!")

**Comment by richardanaya** [comment]
That's awesome!

**Pull request merged**
