### PR TITLE
Chapter 4 in Hungarian

### PR DESCRIPTION
**Pull request by Nemin32**
I like the new system, however, I'd like to ask for a bit of clarification. How should we exactly format these yaml files? When i started editing chapter 4, I saw a lot of seemingly senseless line-breaks in the original version. I ultimately chose to go with line-breaks only where I actually want them to happen.

Anyway, pull introduces Chapter 4 in Hungarian.

### CODE REVIEW

**Comment by richardanaya** [comment]
Sorry about the confusion on that one, YAML parsers are extremely poor right now when it comes to conversion of long text :) definitely format the long text however you think appropriate.

**Comment by Nemin32** [comment]
Oh yeah, no problem at all, I just wanted to make sure.

**Comment by richardanaya** [comment]
So cool seeing these all in one file now :P

**Comment by Nemin32** [comment]
Absolutely! Great change.

**Pull request merged**
