### PR TITLE
translation of chapter 1 to brazilian portuguese

### PR DESCRIPTION
**Pull request by Denstone**

### CODE REVIEW

**Comment by richardanaya** [comment]
Awesome! Welcome to the team :)

**Comment by richardanaya** [comment]
Forgive my ignorance, but what would be the way Brazilian's would call their own language in Brazilian portuguese? So I can add a link to your pages on the front page in the language. :)

**Comment by richardanaya** [comment]
Published at https://tourofrust.com/beta_00_pt.html,  we do releases on Saturday!

**Comment by Denstone** [comment]
> Forgive my ignorance, but what would be the way Brazilian's would call their own language in Brazilian portuguese? So I can add a link to your pages on the front page in the language. :)

We call it "português brasileiro" and the code in ISO 639-1 is "pt-br". Can I use it? The "pt" code refers to the portuguese language speaked in Portugal.

**Comment by richardanaya** [comment]
Sounds great! I can make the updates, no worries :)

**Pull request merged**
