### PR TITLE
Add Occidental/Interlingue for Chapter 7

### PR DESCRIPTION
**Pull request by Dhghomon**

### CODE REVIEW

**Comment by richardanaya** [comment]
Awesome!

**Comment by Dhghomon** [comment]
Thanks! Wasn't sure if you were going to add anything else later but it looked like it's done already.

(I imagine some Playground examples will follow but good to get the main part out of the way)

**Comment by richardanaya** [comment]
Yah :) been a slow week on my side, just started a new job! The text is good! I'll see if I can get some code examples cranked out for tonight so people can enjoy Chapter 7 for the weekend :P

**Comment by Dhghomon** [comment]
Oh nice! Luckily it's nearing completion so even at a slower pace with the new job it'll be easy enough to get it past the finish line.

**Comment by richardanaya** [comment]
For real! Only a few chapters away :P

**Pull request merged**
